spring.application.name=note_forage

# note
spring.datasource.note.jdbc-url=jdbc:postgresql://localhost:5432/note_candidat_new
spring.datasource.note.username=postgres
spring.datasource.note.password=tooknyaina

# forage
spring.datasource.forage.jdbc-url=jdbc:postgresql://localhost:5432/forage
spring.datasource.forage.username=postgres
spring.datasource.forage.password=tooknyaina

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging SQL
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Initialisation des données
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
server.port=9000

logging.level.org.springframework=INFO
logging.level.com.tonpackage=DEBUG