spring.application.name=note
# Configuration PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/note_candidat
spring.datasource.username=postgres
spring.datasource.password=tooknyaina
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging SQL
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Initialisation des données
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
server.port=9000