
DROP TABLE IF EXISTS t_client CASCADE;
DROP TABLE IF EXISTS t_demande CASCADE;
DROP TABLE IF EXISTS t_devis CASCADE;
DROP TABLE IF EXISTS t_type_devis CASCADE;
DROP TABLE IF EXISTS t_statut CASCADE;
DROP TABLE IF EXISTS t_detail_devis CASCADE;
DROP TABLE IF EXISTS t_demande_statut CASCADE;



SET session_replication_role = 'replica';

TRUNCATE TABLE t_client RESTART IDENTITY CASCADE;
TRUNCATE TABLE t_demande RESTART IDENTITY CASCADE;
TRUNCATE TABLE t_devis RESTART IDENTITY CASCADE;
TRUNCATE TABLE t_type_devis RESTART IDENTITY CASCADE;
TRUNCATE TABLE t_statut RESTART IDENTITY CASCADE;
TRUNCATE TABLE t_detail_devis RESTART IDENTITY CASCADE;
TRUNCATE TABLE t_demande_statut RESTART IDENTITY CASCADE;

SET session_replication_role = 'origin';