DROP TABLE IF EXISTS t_candidat CASCADE;
DROP TABLE IF EXISTS t_correcteur CASCADE;
DROP TABLE IF EXISTS t_matiere CASCADE;
DROP TABLE IF EXISTS t_resolution CASCADE;
DROP TABLE IF EXISTS t_operateur CASCADE;
DROP TABLE IF EXISTS t_parametre CASCADE;
DROP TABLE IF EXISTS t_note CASCADE;


SET session_replication_role = 'replica';

TRUNCATE TABLE t_candidat RESTART IDENTITY CASCADE;
TRUNCATE TABLE t_correcteur RESTART IDENTITY CASCADE;
TRUNCATE TABLE t_matiere RESTART IDENTITY CASCADE;
TRUNCATE TABLE t_resolution RESTART IDENTITY CASCADE;
TRUNCATE TABLE t_operateur RESTART IDENTITY CASCADE;
TRUNCATE TABLE t_parametre RESTART IDENTITY CASCADE;
TRUNCATE TABLE t_note RESTART IDENTITY CASCADE;

SET session_replication_role = 'origin';